# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnapterAT3 < Formula
  desc "Command-line tool for Enapter Energy Management System Toolkit"
  homepage "https://github.com/Enapter/enapter-cli"
  version "3.0.0-alpha.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-alpha.9/enapter-cli-3.0.0-alpha.9-darwin-amd64.tar.gz"
      sha256 "d5606b9ee497dd0df6ba669a82a1aeafbb69df63f5ed48909d0fb497aebf87f4"

      def install
        bin.install "enapter3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-alpha.9/enapter-cli-3.0.0-alpha.9-darwin-arm64.tar.gz"
      sha256 "94195e522953462cb9d14291217046bb9e0b57a37cab641ecd5d059e98c240db"

      def install
        bin.install "enapter3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-alpha.9/enapter-cli-3.0.0-alpha.9-linux-amd64.tar.gz"
        sha256 "7320685270ceec926ab7273fd6a4f81aeba5ba7e5fafdc1a7a95dddc4eaf7bb2"

        def install
          bin.install "enapter3"
        end
      end
    end
  end

  test do
    assert_match "Enapter CLI #{version}", shell_output("#{bin}/enapter3 --version")
  end
end
