# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnapterAT3 < Formula
  desc "Command-line tool for Enapter Energy Management System Toolkit"
  homepage "https://github.com/Enapter/enapter-cli"
  version "3.0.0-beta.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-beta.8/enapter-cli-3.0.0-beta.8-darwin-amd64.tar.gz"
      sha256 "7b35a1ce9baed48ac6da11501af01f4fef8086cd1431a5bc860451671a8be3da"

      define_method(:install) do
        bin.install "enapter3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-beta.8/enapter-cli-3.0.0-beta.8-darwin-arm64.tar.gz"
      sha256 "5ae7688efd8bda24ae837b937d5971475644a93a2818b5503bdabdd3f67082da"

      define_method(:install) do
        bin.install "enapter3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-beta.8/enapter-cli-3.0.0-beta.8-linux-amd64.tar.gz"
      sha256 "133034aa0ffd81c940b136fa0e24f0070e1c34420329134f06205ba5f503f8f7"
      define_method(:install) do
        bin.install "enapter3"
      end
    end
  end

  test do
    assert_match "Enapter CLI #{version}", shell_output("#{bin}/enapter3 --version")
  end
end
