# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnapterAT3 < Formula
  desc "Command-line tool for Enapter Energy Management System Toolkit"
  homepage "https://github.com/Enapter/enapter-cli"
  version "3.0.0-alpha.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-alpha.14/enapter-cli-3.0.0-alpha.14-darwin-amd64.tar.gz"
      sha256 "068587f4e2c00f27b80a5e2d451d8e9fa33653499926f726469d352a9deeeee6"

      def install
        bin.install "enapter3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-alpha.14/enapter-cli-3.0.0-alpha.14-darwin-arm64.tar.gz"
      sha256 "f17e0a64b1c54f8f59b33f7d5812f251c1915a77976d74919fa0b186b3266c40"

      def install
        bin.install "enapter3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/enapter/enapter-cli/releases/download/v3.0.0-alpha.14/enapter-cli-3.0.0-alpha.14-linux-amd64.tar.gz"
      sha256 "36154278eeb1c40ab605e17998cf303e560f970c1ba486b98fca21a44b012029"
      def install
        bin.install "enapter3"
      end
    end
  end

  test do
    assert_match "Enapter CLI #{version}", shell_output("#{bin}/enapter3 --version")
  end
end
